name: shop_online
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  awesome_dialog: ^3.2.1
  badges: ^3.1.2
  elegant_notification: ^2.5.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  provider: ^6.1.5
  readmore: ^3.0.0
  redacted: ^1.0.13
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    #- assets/images/accessories/
    #- assets/images/categories/
    #- assets/images/shoes/
    - assets/images/clothes/